### ISSUE TITLE
AAM uses node type equals IAAS or equals PAAS

### ISSUE THREAD

**Issue by rosogon** [SeaCloudsEU/SeaCloudsPlatform#167]
The node types in the AAM contains (e.g.) the following:

```
node_types:
  sc_req.www:
    derived_from: seaclouds.nodes.SoftwareComponent
    properties:
      resource_type:
        constraints:
        - equal: IAAS
```

Instead of "IAAS", it should say "compute".
Instead of "PAAS", it should say "platform".
