### ISSUE TITLE
Non-exist TOSCA policies types

### ISSUE THREAD

**Issue by kiuby88** [SeaCloudsEU/SeaCloudsPlatform#198]
TOSCA policies should contains a defined type. Probably, it should be added from AAM writer.
Below, a set of policies is shown. Each policy must contain a type.
```
groups:
  operation_www:
    members: [www]
    policies:
    - QoSInfo: {execution_time: 200 ms, benchmark_platform: hp_cloud_services.2xl}
    - dependencies: {operation_webservices: '2'}
    - QoSRequirements:
        response_time: {less_than: 2000.0 ms}
        availability: {greater_than: 0.98}
        cost: {less_or_equal: 200.0 euros_per_month}
        workload: {less_or_equal: 50.0 req_per_min}
    - ExpectedQualityPOC: {expectedExecutionTimePOC: .NaN, fitnessPOC: .NaN, expectedCostPOC: 2571.84}
  operation_webservices:
    members: [webservices]
    policies:
    - QoSInfo: {execution_time: 100 ms, benchmark_platform: hp_cloud_services.2xl}
    - dependencies: {operation_db1: '1'}
```
For example
```
    policies:
    - QoSInfo:
        type: seaclouds.policies.qos.info
        execution_time: 100 ms
        benchmark_platform: hp_cloud_services.2xl
```
