### ISSUE TITLE
The credential editor is not working properly

### ISSUE THREAD

**Issue by adriannieto** [SeaCloudsEU/SeaCloudsPlatform#228]
After the DAM is generated, the credential editor is raising an exception due a mismatch on the expected DAM syntax. @rosogon  could you take a look?

**DAM**
```yaml
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: fasf
imports: ['tosca-normative-types:1.0.0.wd06-SNAPSHOT']
topology_template:
  node_templates:
    asfasf:
      type: sc_req.asfasf
      properties: {autoscale: false}
      requirements:
      - {host: DigitalOcean_1gb_ny1}
    DigitalOcean_1gb_ny1:
      type: seaclouds.nodes.Compute.DigitalOcean
      properties: {num_cpus: 1, country: United States, cost: 0.013, hardwareId: 1gb,
        city: NEW YORK, disk_type: ssd, resource_type: compute, disk_size: 30, location: 'digitalocean:compute',
        availability: 0.9999, region: ny1, ram: 1, performance: 140}
    modacloudsDc_asfasf:
      interfaces:
        Standard: {start: 'https://s3-eu-west-1.amazonaws.com/modacloudsdc-start-script/installModacloudsDc.sh'}
      properties:
        shell.env: {MODACLOUDS_TOWER4CLOUDS_DC_SYNC_PERIOD: '10', MODACLOUDS_TOWER4CLOUDS_VM_ID: DigitalOcean_1gb_ny1_ID,
          MODACLOUDS_TOWER4CLOUDS_INFLUXDB_IP: 52.48.12.68, MODACLOUDS_TOWER4CLOUDS_MANAGER_PORT: '8170',
          MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_ID: asfasf_ID, MODACLOUDS_TOWER4CLOUDS_INFLUXDB_PORT: '8086',
          MODACLOUDS_TOWER4CLOUDS_RESOURCES_KEEP_ALIVE_PERIOD: '25', MODACLOUDS_TOWER4CLOUDS_MANAGER_IP: 52.48.12.68,
          MODACLOUDS_TOWER4CLOUDS_VM_TYPE: DigitalOcean_1gb_ny1, MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_TYPE: asfasf}
        install.latch: $brooklyn:component("asfasf").attributeWhenReady("service.isUp")
      type: seaclouds.nodes.Datacollector
      requirements: {host: DigitalOcean_1gb_ny1}
  groups:
    operation_asfasf:
      members: [asfasf]
      policies:
      - dependencies: {type: seaclouds.policies.dependencies}
      - AppQoSRequirements:
          response_time: {less_than: 22.0 ms}
          availability: {greater_than: 0.22}
          cost: {less_or_equal: 22.0 euros_per_month}
          workload: {less_or_equal: 1320.0 req_per_min}
          type: seaclouds.policies.AppQoSRequirements
      - ExpectedQualityPOC: {expectedAvailabilityPOC: 0.9999, fitnessPOC: 42.35042735042735,
          expectedCostPOC: 9.36, type: seaclouds.policies.ExpectedQualityPOC}
      - autoscaling: {maxPoolSize: 3, metric: '$brooklyn:sensor("seaclouds.nodes.ControlledDynamicWebAppCluster",
            "webapp.reqs.perSec.windowed.perNode")', minPoolSize: 1, metricUpperBound: .inf,
          type: seaclouds.policies.autoscalling.AutoscalerPolicy, metricLowerBound: .inf}
    add_brooklyn_location_DigitalOcean_1gb_ny1:
      policies:
      - {brooklyn.location: 'digitalocean:compute:ny1'}
      members: [DigitalOcean_1gb_ny1]
    monitoringInformation:
      policies:
      - monitoringrules.information.policy: {id: 501eae55-08f6-44b5-8226-f7c356d7b80b,
          type: seaclouds.policies.monitoringrules}
      members: [application]
    sla_gen_info:
      policies:
      - seaclouds.app.information: {id: 49913fd4-a40e-4089-9a9e-74fd937eb246, type: seaclouds.policies.app.information}
      members: [application]
node_types:
  sc_req.asfasf:
    derived_from: seaclouds.nodes.ControlledDynamicWebAppCluster
    properties:
      resource_type:
        constraints:
        - {equal: compute}
  seaclouds.nodes.Datacollector:
    derived_from: tosca.nodes.Root
    description: |
      A simple Datacollector
    properties:
      install_latch: {type: string, required: false}
      shell.env:
        type: map
        required: false
        entry_schema: {type: string}
    requirements:
    - {host: tosca.nodes.Compute, type: tosca.relationships.HostedOn}
template_name: seaclouds.app.TpGiKSFZ
template_version: 1.0.0-SNAPSHOT
``` 

*JS Exception*
```javascript
TypeError: (node_template.requirements || []).filter is not a function
    at http://localhost:8000/static/lib/angular-topology-editor/credentials.js:234:17
    at Array.forEach (native)
    at Object.to_topology (http://localhost:8000/static/lib/angular-topology-editor/credentials.js:230:59)
    at o.angular.module.directive.$timeout.link.scope.drawCanvas (http://localhost:8000/static/lib/angular-topology-editor/angular-topology-editor.js:47:52)
    at http://localhost:8000/static/lib/angular-topology-editor/angular-topology-editor.js:55:31
    at http://localhost:8000/static/js/dependencies.js:13:19245
    at e (http://localhost:8000/static/js/dependencies.js:11:27136)
    at http://localhost:8000/static/js/dependencies.js:11:28590
```
