### ISSUE TITLE
A node template type mismatch between ADP and AAM produces wrong DAM.  This is related to PR #234

### ISSUE THREAD

**Issue by adriannieto** [SeaCloudsEU/SeaCloudsPlatform#229]
I found an issue regarding the database types, more precisely in the ADP .  As you can see in the AAM we define a web/db application made of web tier and a DB. How ever when the ADP is generated the node template type field `sc_req.db` is translated from:

```yaml
sc_req.db:
      derived_from: seaclouds.nodes.database.mysql.MySqlNode
```

into:

```yaml
  sc_req.db:
    derived_from: seaclouds.nodes.ControlledDynamicWebAppCluster
```

which is obviously wrong. Could @rosogon @perezp  @PaoloCifariello @kiuby88  take a look of this? It seems to me a mismatch between modules.

**AAM**:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Webchat
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    web:
      type: sc_req.web
      properties:
        language: JAVA
        autoscale: false
        java_version:
          constraints:
          - greater_or_equal: '7'
          - less_or_equal: '7'
      requirements:
      - endpoint: db
    db:
      type: sc_req.db
      properties:
        autoscale: false
        mysql_version:
          constraints:
          - greater_or_equal: '5'
          - less_or_equal: '5'
node_types:
  sc_req.web:
    derived_from: seaclouds.nodes.webapp.jboss.JBoss7Server
    properties:
      java_support:
        constraints:
        - equal: true
      jboss_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '7'
  sc_req.db:
    derived_from: seaclouds.nodes.database.mysql.MySqlNode
    properties:
      mysql_support:
        constraints:
        - equal: true
      mysql_version:
        constraints:
        - greater_or_equal: '5'
        - less_or_equal: '5'
groups:
  operation_web:
    members:
    - web
    policies:
    - dependencies:
        operation_db: '29'
    - AppQoSRequirements:
        response_time:
          less_than: 150.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 24000.0 req_per_min
  operation_db:
    members:
    - db
    policies:
    - dependencies: {}
```
**ADP**:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Webchat
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    web:
      type: sc_req.web
      properties:
        language: JAVA
        autoscale: false
        java_version:
          constraints:
          - greater_or_equal: '7'
          - less_or_equal: '7'
      requirements:
      - endpoint: db
      - host: OpenShift_Online_Europe_IE
        instancesPOC: 5
    db:
      type: sc_req.db
      properties:
        autoscale: false
        mysql_version:
          constraints:
          - greater_or_equal: '5'
          - less_or_equal: '5'
      requirements:
      - host: brightbox_Europe_GB
        instancesPOC: 2
    brightbox_Europe_GB:
      type: seaclouds.nodes.Platform.brightbox
      properties:
        mysql_version: 5.0
        continent: Europe
        country: GB
        horizontal_scaling: true
        ruby_support: true
        private_hosting: false
        resource_type: platform
        ruby_version: 1.9.3
        vertical_scaling: true
        auto_scaling: false
        mysql_support: true
        public_hosting: true
        performance: 34
        availability: 0.99561
        cost: 0.51
    OpenShift_Online_Europe_IE:
      type: seaclouds.nodes.Platform.OpenShift_Online
      properties:
        continent: Europe
        country: IE
        postgresql_support: true
        php_version: 5.4
        auto_scaling: true
        jboss_support: true
        postgresql_version: 9.2
        horizontal_scaling: true
        python_version: 3.3
        vertical_scaling: true
        jboss_version: 8.0
        php_support: true
        node_support: true
        tomcat_version: 7
        private_hosting: false
        mongodb_version: 2.4
        resource_type: platform
        node_version: 0.6
        ruby_version: 2.0
        tomcat_support: true
        mongodb_support: true
        public_hosting: true
        mysql_version: 5.5
        java_support: true
        python_support: true
        ruby_support: true
        java_version: 7
        mysql_support: true
        performance: 112
        availability: 0.99175
        cost: 0.02
node_types:
  sc_req.web:
    derived_from: seaclouds.nodes.webapp.jboss.JBoss7Server
    properties:
      java_support:
        constraints:
        - equal: true
      jboss_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '7'
  sc_req.db:
    derived_from: seaclouds.nodes.ControlledDynamicWebAppCluster
    properties:
      mysql_support:
        constraints:
        - equal: true
      mysql_version:
        constraints:
        - greater_or_equal: '5'
        - less_or_equal: '5'
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId:
        required: false
        type: string
groups:
  operation_web:
    members:
    - web
    policies:
    - dependencies:
        operation_db: '29'
    - AppQoSRequirements:
        response_time:
          less_than: 150.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 24000.0 req_per_min
    - ExpectedQualityPOC:
        expectedAvailabilityPOC: 0.9999807278617826
        fitnessPOC: 41.24007936507937
        expectedCostPOC: 806.4000000000001
  operation_db:
    members:
    - db
    policies:
    - dependencies: {}
    - autoscaling:
        maxPoolSize: 3
        metric: $brooklyn:sensor("seaclouds.nodes.ControlledDynamicWebAppCluster", "webapp.reqs.perSec.windowed.perNode")
        minPoolSize: 1
        metricUpperBound: .inf
        type: seaclouds.policies.autoscalling.AutoscalerPolicy
        metricLowerBound: .inf
```

**DAM**:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Webchat
imports: ['tosca-normative-types:1.0.0.wd06-SNAPSHOT']
topology_template:
  node_templates:
    web:
      type: sc_req.web
      properties:
        language: JAVA
        autoscale: false
        java_version:
          constraints:
          - {greater_or_equal: '7'}
          - {less_or_equal: '7'}
      requirements:
      - {endpoint: db}
      - {host: OpenShift_Online_Europe_IE}
    db:
      type: sc_req.db
      properties:
        autoscale: false
        mysql_version:
          constraints:
          - {greater_or_equal: '5'}
          - {less_or_equal: '5'}
      requirements:
      - {host: brightbox_Europe_GB}
    brightbox_Europe_GB:
      type: seaclouds.nodes.Platform.brightbox
      properties: {mysql_version: 5.0, continent: Europe, country: GB, horizontal_scaling: true,
        ruby_support: true, private_hosting: false, resource_type: platform, ruby_version: 1.9.3,
        vertical_scaling: true, auto_scaling: false, mysql_support: true, public_hosting: true,
        performance: 34, availability: 0.99561, cost: 0.51}
    OpenShift_Online_Europe_IE:
      type: seaclouds.nodes.Platform.OpenShift_Online
      properties: {continent: Europe, country: IE, postgresql_support: true, php_version: 5.4,
        auto_scaling: true, jboss_support: true, postgresql_version: 9.2, horizontal_scaling: true,
        python_version: 3.3, vertical_scaling: true, jboss_version: 8.0, php_support: true,
        node_support: true, tomcat_version: 7, private_hosting: false, mongodb_version: 2.4,
        resource_type: platform, node_version: 0.6, ruby_version: 2.0, tomcat_support: true,
        mongodb_support: true, public_hosting: true, mysql_version: 5.5, java_support: true,
        python_support: true, ruby_support: true, java_version: 7, mysql_support: true,
        performance: 112, availability: 0.99175, cost: 0.02}
    javaAppDc_web:
      interfaces:
        Standard: {start: 'https://s3-eu-west-1.amazonaws.com/java-app-dc-start-script/installJavaAppDc.sh'}
      properties:
        install.latch: $brooklyn:component("web").attributeWhenReady("service.isUp")
        env: {MODULE_ID: web, MODACLOUDS_TOWER4CLOUDS_INFLUXDB_IP: 52.48.12.68, MODACLOUDS_TOWER4CLOUDS_MANAGER_PORT: '8170',
          MODACLOUDS_TOWER4CLOUDS_INFLUXDB_PORT: '8170', MODACLOUDS_TOWER4CLOUDS_MANAGER_IP: 52.48.12.68}
      type: seaclouds.nodes.Datacollector
      requirements: {host: OpenShift_Online_Europe_IE}
  groups:
    operation_web:
      members: [web]
      policies:
      - dependencies: {operation_db: '29', type: seaclouds.policies.dependencies}
      - AppQoSRequirements:
          response_time: {less_than: 150.0 ms}
          availability: {greater_than: 0.99}
          cost: {less_or_equal: 1000.0 euros_per_month}
          workload: {less_or_equal: 24000.0 req_per_min}
          type: seaclouds.policies.AppQoSRequirements
      - ExpectedQualityPOC: {expectedAvailabilityPOC: 0.9999807278617826, fitnessPOC: 41.24007936507937,
          expectedCostPOC: 806.4000000000001, type: seaclouds.policies.ExpectedQualityPOC}
    operation_db:
      members: [db]
      policies:
      - dependencies: {type: seaclouds.policies.dependencies}
      - autoscaling: {maxPoolSize: 3, metric: '$brooklyn:sensor("seaclouds.nodes.ControlledDynamicWebAppCluster",
            "webapp.reqs.perSec.windowed.perNode")', minPoolSize: 1, metricUpperBound: .inf,
          type: seaclouds.policies.autoscalling.AutoscalerPolicy, metricLowerBound: .inf}
    add_brooklyn_location_OpenShift_Online_Europe_IE:
      policies:
      - {brooklyn.location: OpenShift_Online_Europe_IE}
      members: [OpenShift_Online_Europe_IE]
    add_brooklyn_location_brightbox_Europe_GB:
      policies:
      - {brooklyn.location: brightbox_Europe_GB}
      members: [brightbox_Europe_GB]
    monitoringInformation:
      policies:
      - monitoringrules.information.policy: {id: bd5fd0ec-f5ff-4297-a723-f651e3b0376a,
          type: seaclouds.policies.monitoringrules}
      members: [application]
    sla_gen_info:
      policies:
      - seaclouds.app.information: {id: 2d62234f-e70d-424f-bf1f-e2af5f34a316, type: seaclouds.policies.app.information}
      members: [application]
node_types:
  sc_req.db:
    derived_from: seaclouds.nodes.ControlledDynamicWebAppCluster
    properties:
      mysql_support:
        constraints:
        - {equal: true}
      mysql_version:
        constraints:
        - {greater_or_equal: '5'}
        - {less_or_equal: '5'}
  sc_req.web:
    derived_from: seaclouds.nodes.webapp.jboss.JBoss7Server
    properties:
      java_support:
        constraints:
        - {equal: true}
      jboss_support:
        constraints:
        - {equal: true}
      java_version:
        constraints:
        - {greater_or_equal: '7'}
        - {less_or_equal: '7'}
  seaclouds.nodes.Datacollector:
    derived_from: tosca.nodes.Root
    description: |
      A simple Datacollector
    properties:
      install_latch: {type: string, required: false}
      shell.env:
        type: map
        required: false
        entry_schema: {type: string}
    requirements:
    - {host: tosca.nodes.Compute, type: tosca.relationships.HostedOn}
template_name: seaclouds.app.bE2Da8wc
template_version: 1.0.0-SNAPSHOT
```
