### ISSUE TITLE
5 identical results in the "Optimize & Plan" step

### ISSUE THREAD

**Issue by rsucasas** [SeaCloudsEU/SeaCloudsPlatform#240]
I get 5 identical results in the "Optimize & Plan" step.

AAM:
```
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    forum-webapp-20151021:
      type: sc_req.forum-webapp-20151021
      properties:
        language: JAVA
        autoscale: false
node_types:
  sc_req.forum-webapp-20151021:
    derived_from: seaclouds.nodes.webapp.tomcat.TomcatServer
    properties:
      java_support:
        constraints:
        - equal: true
      tomcat_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '8'
      resource_type:
        constraints:
        - equal: platform
groups:
  operation_forum-webapp-20151021:
    members:
    - forum-webapp-20151021
    policies:
    - QoSInfo:
        execution_time: 100 ms
        benchmark_platform: Amazon_EC2_m1_medium_us_east_1
    - dependencies: {}
    - AppQoSRequirements:
        response_time:
          less_than: 200.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 2400.0 req_per_min
```

These are the ADPs I get:
```
["tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    forum-webapp-20151021:
      type: sc_req.forum-webapp-20151021
      properties:
        language: JAVA
        autoscale: false
      requirements:
      - host: Cloud_Foundry
        instancesPOC: 1
    Cloud_Foundry:
      type: seaclouds.nodes.Platform.Cloud_Foundry
      properties:
        node_support: true
        go_support: true
        tomcat_version: 7
        private_hosting: true
        resource_type: platform
        tomcat_support: true
        auto_scaling: false
        public_hosting: false
        java_support: true
        horizontal_scaling: true
        ruby_support: true
        python_support: true
        scala_support: true
        vertical_scaling: true
        location: CloudFoundry
        go_version: 1.4
        php_support: true
        performance: 192
        availability: 0.99871
        cost: 0.04
node_types:
  sc_req.forum-webapp-20151021:
    derived_from: seaclouds.nodes.webapp.tomcat.TomcatServer
    properties:
      java_support:
        constraints:
        - equal: true
      tomcat_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '8'
      resource_type:
        constraints:
        - equal: platform
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId:
        required: false
        type: string
groups:
  operation_forum-webapp-20151021:
    members:
    - forum-webapp-20151021
    policies:
    - QoSInfo:
        execution_time: 100 ms
        benchmark_platform: Amazon_EC2_m1_medium_us_east_1
    - dependencies: {}
    - AppQoSRequirements:
        response_time:
          less_than: 200.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 2400.0 req_per_min
    - ExpectedQualityPOC:
        expectedAvailabilityPOC: 0.99871
        fitnessPOC: 0.6666666666666666
        expectedCostPOC: 28.8
        expectedExecutionTimePOC: .inf
", "tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    forum-webapp-20151021:
      type: sc_req.forum-webapp-20151021
      properties:
        language: JAVA
        autoscale: false
      requirements:
      - host: Cloud_Foundry
        instancesPOC: 1
    Cloud_Foundry:
      type: seaclouds.nodes.Platform.Cloud_Foundry
      properties:
        node_support: true
        go_support: true
        tomcat_version: 7
        private_hosting: true
        resource_type: platform
        tomcat_support: true
        auto_scaling: false
        public_hosting: false
        java_support: true
        horizontal_scaling: true
        ruby_support: true
        python_support: true
        scala_support: true
        vertical_scaling: true
        location: CloudFoundry
        go_version: 1.4
        php_support: true
        performance: 192
        availability: 0.99871
        cost: 0.04
node_types:
  sc_req.forum-webapp-20151021:
    derived_from: seaclouds.nodes.webapp.tomcat.TomcatServer
    properties:
      java_support:
        constraints:
        - equal: true
      tomcat_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '8'
      resource_type:
        constraints:
        - equal: platform
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId:
        required: false
        type: string
groups:
  operation_forum-webapp-20151021:
    members:
    - forum-webapp-20151021
    policies:
    - QoSInfo:
        execution_time: 100 ms
        benchmark_platform: Amazon_EC2_m1_medium_us_east_1
    - dependencies: {}
    - AppQoSRequirements:
        response_time:
          less_than: 200.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 2400.0 req_per_min
    - ExpectedQualityPOC:
        expectedAvailabilityPOC: 0.99871
        fitnessPOC: 0.6666666666666666
        expectedCostPOC: 28.8
        expectedExecutionTimePOC: .inf
", "tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    forum-webapp-20151021:
      type: sc_req.forum-webapp-20151021
      properties:
        language: JAVA
        autoscale: false
      requirements:
      - host: Cloud_Foundry
        instancesPOC: 1
    Cloud_Foundry:
      type: seaclouds.nodes.Platform.Cloud_Foundry
      properties:
        node_support: true
        go_support: true
        tomcat_version: 7
        private_hosting: true
        resource_type: platform
        tomcat_support: true
        auto_scaling: false
        public_hosting: false
        java_support: true
        horizontal_scaling: true
        ruby_support: true
        python_support: true
        scala_support: true
        vertical_scaling: true
        location: CloudFoundry
        go_version: 1.4
        php_support: true
        performance: 192
        availability: 0.99871
        cost: 0.04
node_types:
  sc_req.forum-webapp-20151021:
    derived_from: seaclouds.nodes.webapp.tomcat.TomcatServer
    properties:
      java_support:
        constraints:
        - equal: true
      tomcat_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '8'
      resource_type:
        constraints:
        - equal: platform
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId:
        required: false
        type: string
groups:
  operation_forum-webapp-20151021:
    members:
    - forum-webapp-20151021
    policies:
    - QoSInfo:
        execution_time: 100 ms
        benchmark_platform: Amazon_EC2_m1_medium_us_east_1
    - dependencies: {}
    - AppQoSRequirements:
        response_time:
          less_than: 200.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 2400.0 req_per_min
    - ExpectedQualityPOC:
        expectedAvailabilityPOC: 0.99871
        fitnessPOC: 0.6666666666666666
        expectedCostPOC: 28.8
        expectedExecutionTimePOC: .inf
", "tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    forum-webapp-20151021:
      type: sc_req.forum-webapp-20151021
      properties:
        language: JAVA
        autoscale: false
      requirements:
      - host: Cloud_Foundry
        instancesPOC: 1
    Cloud_Foundry:
      type: seaclouds.nodes.Platform.Cloud_Foundry
      properties:
        node_support: true
        go_support: true
        tomcat_version: 7
        private_hosting: true
        resource_type: platform
        tomcat_support: true
        auto_scaling: false
        public_hosting: false
        java_support: true
        horizontal_scaling: true
        ruby_support: true
        python_support: true
        scala_support: true
        vertical_scaling: true
        location: CloudFoundry
        go_version: 1.4
        php_support: true
        performance: 192
        availability: 0.99871
        cost: 0.04
node_types:
  sc_req.forum-webapp-20151021:
    derived_from: seaclouds.nodes.webapp.tomcat.TomcatServer
    properties:
      java_support:
        constraints:
        - equal: true
      tomcat_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '8'
      resource_type:
        constraints:
        - equal: platform
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId:
        required: false
        type: string
groups:
  operation_forum-webapp-20151021:
    members:
    - forum-webapp-20151021
    policies:
    - QoSInfo:
        execution_time: 100 ms
        benchmark_platform: Amazon_EC2_m1_medium_us_east_1
    - dependencies: {}
    - AppQoSRequirements:
        response_time:
          less_than: 200.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 2400.0 req_per_min
    - ExpectedQualityPOC:
        expectedAvailabilityPOC: 0.99871
        fitnessPOC: 0.6666666666666666
        expectedCostPOC: 28.8
        expectedExecutionTimePOC: .inf
", "tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare
imports:
- tosca-normative-types:1.0.0.wd06-SNAPSHOT
topology_template:
  node_templates:
    forum-webapp-20151021:
      type: sc_req.forum-webapp-20151021
      properties:
        language: JAVA
        autoscale: false
      requirements:
      - host: Cloud_Foundry
        instancesPOC: 1
    Cloud_Foundry:
      type: seaclouds.nodes.Platform.Cloud_Foundry
      properties:
        node_support: true
        go_support: true
        tomcat_version: 7
        private_hosting: true
        resource_type: platform
        tomcat_support: true
        auto_scaling: false
        public_hosting: false
        java_support: true
        horizontal_scaling: true
        ruby_support: true
        python_support: true
        scala_support: true
        vertical_scaling: true
        location: CloudFoundry
        go_version: 1.4
        php_support: true
        performance: 192
        availability: 0.99871
        cost: 0.04
node_types:
  sc_req.forum-webapp-20151021:
    derived_from: seaclouds.nodes.webapp.tomcat.TomcatServer
    properties:
      java_support:
        constraints:
        - equal: true
      tomcat_support:
        constraints:
        - equal: true
      java_version:
        constraints:
        - greater_or_equal: '7'
        - less_or_equal: '8'
      resource_type:
        constraints:
        - equal: platform
  seaclouds.nodes.Compute:
    derived_from: tosca.nodes.Compute
    description: Custom compute
    properties:
      hardwareId:
        required: false
        type: string
groups:
  operation_forum-webapp-20151021:
    members:
    - forum-webapp-20151021
    policies:
    - QoSInfo:
        execution_time: 100 ms
        benchmark_platform: Amazon_EC2_m1_medium_us_east_1
    - dependencies: {}
    - AppQoSRequirements:
        response_time:
          less_than: 200.0 ms
        availability:
          greater_than: 0.99
        cost:
          less_or_equal: 1000.0 euros_per_month
        workload:
          less_or_equal: 2400.0 req_per_min
    - ExpectedQualityPOC:
        expectedAvailabilityPOC: 0.99871
        fitnessPOC: 0.6666666666666666
        expectedCostPOC: 28.8
        expectedExecutionTimePOC: .inf
"]
```
