### ISSUE TITLE
Errors in the validation of a TOSCA DAM generated by the Dashboard for a web app (PaaS)

### ISSUE THREAD

**Issue by rsucasas** [SeaCloudsEU/SeaCloudsPlatform#244]
This is the DAM created by the dashboard (http://95.211.172.242:8001/#/wizards/add-application) for a single java web application that should be deployed in a PaaS provider:
```
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: Softcare_v1
imports:
  - 'tosca-normative-types:1.0.0.wd06-SNAPSHOT'
topology_template:
  node_templates:
    webApp:
      type: org.apache.brooklyn.entity.webapp.tomcat.TomcatServer
      properties:
        language: JAVA
        location: STATIC
        location_option: AMERICA
        autoscale: false
      requirements:
        - host: Cloud_Foundry
    Cloud_Foundry:
      type: tosca.nodes.Platform
      properties:
        node_support: true
        go_support: true
        tomcat_version: 7
        private_hosting: true
        resource_type: platform
        tomcat_support: true
        auto_scaling: false
        public_hosting: false
        java_support: true
        horizontal_scaling: true
        ruby_support: true
        python_support: true
        scala_support: true
        vertical_scaling: true
        location: CloudFoundry
        go_version: 1.4
        php_support: true
        performance: 192
        availability: 0.99871
        cost: 0.04
  groups:
    operation_webApp:
      members:
        - webApp
      policies:
        - QoSInfo:
            execution_time: 5 ms
            benchmark_platform: Amazon_EC2_m1_medium_us_east_1
            type: seaclouds.policies.QoSInfo
        - dependencies:
            type: seaclouds.policies.dependencies
        - AppQoSRequirements:
            response_time:
              less_than: 200.0 ms
            availability:
              greater_than: 0.99
            cost:
              less_or_equal: 1000.0 euros_per_month
            workload:
              less_or_equal: 300.0 req_per_min
            type: seaclouds.policies.AppQoSRequirements
        - ExpectedQualityPOC:
            expectedAvailabilityPOC: 0.99871
            fitnessPOC: 47.75193798449605
            expectedCostPOC: 28.8
            expectedExecutionTimePOC: 0.004038257173219979
            type: seaclouds.policies.ExpectedQualityPOC
    add_brooklyn_location_Cloud_Foundry:
      policies:
        - brooklyn.location: CloudFoundry
      members:
        - Cloud_Foundry
    monitoringInformation:
      policies:
        - monitoringrules.information.policy:
            id: 20187676-b392-4306-8b50-901f8a6aab65
            type: seaclouds.policies.monitoringrules
      members:
        - application
    sla_gen_info:
      policies:
        - seaclouds.app.information:
            id: 6e3d444d-917b-44c9-89e7-0095e6e3bb70
            type: seaclouds.policies.app.information
      members:
        - application
node_types:
  org.apache.brooklyn.entity.webapp.tomcat.TomcatServer:
    derived_from: tosca.nodes.Root
    description: |
      A simple Tomcat server
    properties:
      http.port:
        type: list
        required: false
        entry_schema:
          type: string
      java.sysprops:
        type: map
        required: false
        entry_schema:
          type: string
      wars.root:
        type: string
        required: false
    requirements:
      - host: tosca.nodes.Compute
        type: tosca.relationships.HostedOn
  seaclouds.nodes.Datacollector:
    derived_from: tosca.nodes.Root
    description: |
      A simple DC
    properties:
      install_latch:
        type: string
        required: false
      shell.env:
        type: map
        required: false
        entry_schema:
          type: string
    requirements:
      - host: tosca.nodes.Compute
        type: tosca.relationships.HostedOn
template_name: seaclouds.app.JBkCjgWn
template_version: 1.0.0-SNAPSHOT

```

The problems are the following:
1. I'm unable to deploy the application using the dashboard.
2. When I try to deploy this application using brooklyn (http://52.31.210.230:8081/ ) I get the following errors:
```
Unable to instantiate item; 2 errors including: Transformer for tosca gave an error creating this plan: Could not parse submitted-tosca-plan as TOSCA: 

Context: Derived_from type not found 
Problem: The type specified for a node_template is not found neither in the archive nor its dependencies. 
Note: tosca.nodes.Platform 
Start: SimpleMark(line=17, column=7) 
End : SimpleMark(line=39, column=3) 
Level: ERROR
Code : TYPE_NOT_FOUND 

Context: null Problem: null Note: application Start: SimpleMark(line=6, column=3) End : SimpleMark(line=85, column=1) Level: WARNING Code : UNKOWN_GROUP_MEMBER 

Context: null Problem: null Note: application Start: SimpleMark(line=6, column=3) End : SimpleMark(line=85, column=1) Level: WARNING Code : UNKOWN_GROUP_MEMBER 

Context: null Problem: null Note: host Start: SimpleMark(line=15, column=17) End : SimpleMark(line=15, column=30) Level: ERROR Code : REQUIREMENT_CAPABILITY_NOT_FOUND 

Context: null Problem: null Note: host Start: SimpleMark(line=15, column=17) End : SimpleMark(line=15, column=30) Level: WARNING Code : RELATIONSHIP_NOT_BUILT
```

**Comment by rosogon** [comment]
@PaoloCifariello, @kiuby88, @jacopogiallo : There is also another problem with this DAM. 

This policy:
```
    add_brooklyn_location_Cloud_Foundry:
      policies:
        - brooklyn.location: CloudFoundry
```

should be
```
    add_brooklyn_location_Cloud_Foundry:
      policies:
        - brooklyn.location: 
             CloudFoundry: {}
```

i.e. CloudFoundry should be a map (the credentials will be stored within), not a string.
