### ISSUE TITLE
Location in AAM

### ISSUE THREAD

**Issue by rosogon** [SeaCloudsEU/SeaCloudsPlatform#275]
The location is not being taken into account by the matchmaker.

The right format in the AAM should be:

```
 sc_req.www:
    derived_from: seaclouds.nodes.php.httpd.PhpHttpdServer
    properties:
      resource_type:
        constraints:
        - equal: compute
      continent:
        constraints:
        - equal: Europe
```
